# Generated by Django 5.2.4 on 2025-07-21 01:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(choices=[('ANGELICA', 'Angélica'), ('CAMELIA', 'Camélia')], max_length=20)),
                ('estante', models.PositiveIntegerField()),
                ('andar', models.PositiveIntegerField()),
                ('posicao', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
                'unique_together': {('rua', 'estante', 'andar', 'posicao')},
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('CORRENTE', 'Corrente'), ('INTERMEDIARIO', 'Intermediário')], max_length=20)),
                ('anos_para_descarte', models.PositiveIntegerField()),
                ('data_entrada', models.DateField(default=django.utils.timezone.now)),
                ('arquivo_pdf', models.FileField(upload_to='documentos/')),
                ('localizacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='documento', to='documentos.localizacao')),
            ],
            options={
                'ordering': ['-data_entrada'],
            },
        ),
    ]
